### ISSUE TITLE
Build error under Expo Project due to bad include paths

### ISSUE THREAD

**Issue by hernandp** [rh389/react-native-securerandom#8]
We are building an Expo project which includes the RNSecureRandom library.  Unfortunately, we cannot build the library without manually adjusting the Header search paths, as the XCode build system cannot find the RCTDefines.h file.

The header search paths included in your library are

```$(SRCROOT)/../../react-native/React```
```$(SRCROOT)/../../../React```

adding 

```$(SRCROOT)/../../../ios/Pods/Headers/Public```

fixes the problem.

Versions:
react-native-cli: 2.0.1
react-native: 0.57.1
expo-cli: 2.18.7

If you need any additional information, I'll be glad to help.
Thanks.

**Comment by robhogan** [comment]
Hi @hernandp, thanks for the report. I don’t have a lot of experience with expo - I’m guessing this is an ExpoKit project with cocoa pods eg https://docs.expo.io/versions/latest/expokit/expokit/?

It shouldn’t be necessary to adjust header paths for that but it may be that I need to add a dependency in the podspec - I’ll check it out. Thanks again 

Edit: Actually, could you also describe how you installed this library into your project? Cheers

**Comment by hernandp** [comment]
Yes, it's an ExpoKit project with Cocoa Pods.

We integrated the project using npm and react-link. 

```
react-native link react-native-securerandom
```
Thanks.

**Comment by robhogan** [comment]
The problem here was with this project's podspec being outside the root directory - `react-native link` didn't detect that it could be installed as a pod, which it needs to be if `React` is also installed as a pod.

I've pushed a fix for this as `1.0.0-rc.0`

`react-native unlink react-native-securerandom`
`yarn add react-native-securerandom@1.0.0-rc.0`
`react-native link react-native-securerandom`
`cd ios && pod install`

If you could let me know if this works for you that'd be great. Will monitor for stability before publishing `1.0.0`

**Comment by robhogan** [comment]
This fix has now been published for a while and seems to be working for everyone. Closing.
